### ISSUE TITLE
Nav: on mobile, About dropdown items -- two style questions

### ISSUE THREAD

**Issue by cahdeemer** [InteractiveMechanics/uronline#3]
Currently text is aligned right - did you want it that way or centered?
Currently text is sort of small - did you want it that way?

**note: test on Chrome DevTools, not on real devices**

![image](https://cloud.githubusercontent.com/assets/9889294/15865306/41afb22c-2ca8-11e6-994f-f98576624d56.png)

**Comment by mtedeschi** [comment]
Fixed with commit for #2.
